/**
 * Applies syntax colouring to a single line of beautified XML.
 *
 * Returns an HTML string safe to inject via dangerouslySetInnerHTML — the
 * input is always generated by our own beautifier, never raw user content.
 * HTML-special characters are escaped before any spans are added.
 *
 * Colour assignments (hex values intentionally match the dark #0d1117 theme):
 *   Tags      #7dd3fc  sky-300
 *   Values    #86efac  green-300
 *   Comments  #6e7681  muted gray (italic)
 *   Decl/PI   #484f58  very muted gray
 */

const TAG_COLOR  = '#7dd3fc'
const VAL_COLOR  = '#86efac'
const CMT_COLOR  = '#6e7681'
const DECL_COLOR = '#484f58'

export function colorizeXmlLine(text: string): string {
  // Step 1: Escape HTML entities, then replace < and > with private-use
  // placeholders so our regex patterns can still match tag boundaries without
  // fighting with HTML entity sequences.
  let s = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '\x01')
    .replace(/>/g, '\x02')

  // Step 2: Comments  <!-- ... -->
  s = s.replace(
    /\x01!--([\s\S]*?)--\x02/g,
    `<em style="color:${CMT_COLOR};font-style:italic">\x01!--$1--\x02</em>`,
  )

  // Step 3: XML declaration / processing instruction  <? ... ?>
  s = s.replace(
    /\x01\?([\s\S]*?)\?\x02/g,
    `<span style="color:${DECL_COLOR}">\x01?$1?\x02</span>`,
  )

  // Step 4: Elements with inline text content  <Tag>value</Tag>
  // We match: opening-tag  text-content  closing-tag — all on one line.
  s = s.replace(
    /(\x01\/?[\w:.-]+\x02)([^\x01]*)(\x01\/[\w:.-]+\x02)/g,
    (_, open, value, close) => {
      const openStyled  = wrapTag(open)
      const closeStyled = wrapTag(close)
      const valueStyled = value
        ? `<span style="color:${VAL_COLOR}">${value}</span>`
        : ''
      return openStyled + valueStyled + closeStyled
    },
  )

  // Step 5: Any remaining tag tokens (opening, closing, self-closing)
  s = s.replace(
    /\x01(\/?[\w:.-]+)\x02/g,
    `<span style="color:${TAG_COLOR}">\x01$1\x02</span>`,
  )

  // Step 6: Restore placeholder characters to proper HTML entities
  return s.replace(/\x01/g, '&lt;').replace(/\x02/g, '&gt;')
}

function wrapTag(raw: string): string {
  return raw.replace(
    /\x01(\/?[\w:.-]+)\x02/,
    `<span style="color:${TAG_COLOR}">\x01$1\x02</span>`,
  )
}